### PR TITLE
specify fip subnet based on router

### LINKED ISSUE #615: subnetID not set when creating a floating IP for the bastion vm
**How to categorize this issue?**

/area ops-productivity
/kind bug
/platform openstack

**What happened**:

when creating a floating IP for the bastion vm the subnetID is not set on the CreateOpts [https://github.com/gardener/gardener-extension-provider-openstack/blob/e35f1b04e8a[…]ab94ff9613aef7e375/pkg/controller/bastion/actuator_reconcile.go](https://github.com/gardener/gardener-extension-provider-openstack/blob/e35f1b04e8a50c268306f0ab94ff9613aef7e375/pkg/controller/bastion/actuator_reconcile.go#L178-L181)
This could lead to wrong subnets being used for the floating IP of the bastion. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by kon-angelo**
**How to categorize this PR?**

/area control-plane
/kind enhancement
/platform openstack

**What this PR does / why we need it**:
This PR will make it so that the bastion controller binds FIPs from the same subnet as the router. We can potentially change the logic to use processing logic similar as with `FloatingPoolSubnetName`, but for simplicity this PR chooses the router subnet. The downside of that choice is that we depend on that particular subnet for available FIPs. 

**Which issue(s) this PR fixes**:
Fixes #615 

**Special notes for your reviewer**:

**Release note**:

```other operator
The bastion with try to reserve Floating IPs from the router's external subnet
```

### CODE REVIEW

File: pkg/controller/bastion/actuator_reconcile.go [hunk 1]
```diff
@@ -175,9 +175,28 @@ func ensurePublicIPAddress(opt *Options, log logr.Logger, client openstackclient
...
+	if err != nil {
+		return nil, err
+	}
+
+	if len(routers) == 0 {
+		return nil, fmt.Errorf("router with ID %s was not found", infraStatus.Networks.Router.ID)
+	}
+
+	var subnetID string
+	if router := routers[0]; len(router.GatewayInfo.ExternalFixedIPs) != 0 {
```
Comment (petersutter) [inline pkg/controller/bastion/actuator_reconcile.go:192]: I'm not too deep in the topic. In which case is `ExternalFixedIPs` empty and is this considered an error?

Comment (kon-angelo) [reply pkg/controller/bastion/actuator_reconcile.go:192]: Practically it would mean that there is no FIP attached to the router which would be an error condition for the shoot. It would be an invalid shoot state so we can treat it as an error.

**Review by MartinWeindel — APPROVED** [review]
/lgtm

File: pkg/controller/bastion/actuator_reconcile.go (hunk 1 above)
Comment (petersutter) [reply pkg/controller/bastion/actuator_reconcile.go:192]: will you make another commit to return an error in this case?

Comment (kon-angelo) [reply pkg/controller/bastion/actuator_reconcile.go:192]: @petersutter, yes I will update

File: pkg/controller/bastion/actuator_reconcile.go [hunk 2]
```diff
@@ -175,9 +175,33 @@ func ensurePublicIPAddress(opt *Options, log logr.Logger, client openstackclient
...
+	var (
+		subnetID string
+	)
+
+	router := routerList[0]
+	if len(router.GatewayInfo.ExternalFixedIPs) == 0 {
+		return nil, errors.New("no external fixed IPs detected on the router")
+	}
+
+	subnetID = router.GatewayInfo.ExternalFixedIPs[0].SubnetID
```
Comment (petersutter) [inline pkg/controller/bastion/actuator_reconcile.go:200]:
```suggestion
	router := routerList[0]
	if len(router.GatewayInfo.ExternalFixedIPs) == 0 {
		return nil, errors.New("no external fixed IPs detected on the router")
	}

	subnetID := router.GatewayInfo.ExternalFixedIPs[0].SubnetID
```

**Review by petersutter — APPROVED** [review]
/lgtm

**Review by tedteng — APPROVED** [review]

**Review by MartinWeindel — APPROVED** [review]
/lgtm
